package titanmusicplayer.entity;
// Generated Sep 28, 2013 11:42:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mp3s generated by hbm2java
 */
public class Mp3s  implements java.io.Serializable {


     private int mp3id;
     private String title;
     private String artist;
     private String album;
     private Date length;
     private Date releaseDate;

    public Mp3s() {
    }

	
    public Mp3s(int mp3id) {
        this.mp3id = mp3id;
    }
    public Mp3s(int mp3id, String title, String artist, String album, Date length, Date releaseDate) {
       this.mp3id = mp3id;
       this.title = title;
       this.artist = artist;
       this.album = album;
       this.length = length;
       this.releaseDate = releaseDate;
    }
   
    public int getMp3id() {
        return this.mp3id;
    }
    
    public void setMp3id(int mp3id) {
        this.mp3id = mp3id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getArtist() {
        return this.artist;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public Date getLength() {
        return this.length;
    }
    
    public void setLength(Date length) {
        this.length = length;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }




}


